import './globals.css';
import Navbar from './components/Navbar';
import React from 'react';

export const metadata = {
    title: 'WikiRock!',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className='bg-slate-800'>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
