import React from 'react';

import Header from './components/Header';
import Footer from './components/Footer';

import './styles/reset.scss';
import './styles/globals.scss';

export const metadata = {
    title: 'WikiRock!',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>
                <Header />
                <Footer />
                {children}
            </body>
        </html>
    );
}
